name: build and deploy docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-docs:
    
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.101'
    - name: Restore tools
      run: dotnet tool restore
    - name: Build docs
      working-directory: ./
      run: dotnet fsdocs build --eval
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output 